INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (162, 2, 1, "Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (163, 2, 2, "Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (164, 2, 3, "Thing");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (165, 2, 4, "Marvel Girl");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (166, 2, 5, "Phoenix");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (167, 2, 6, "Sub-Mariner");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (168, 2, 7, "Mister Fantastic");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (169, 2, 8, "Iceman");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (170, 2, 9, "Shadowcat");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (171, 2, 10, "Human Torch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (172, 2, 11, "Nightcrawler");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (173, 2, 12, "Captain Britain");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (174, 2, 13, "Iron Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (175, 2, 14, "Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (176, 2, 15, "Cable");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (177, 2, 16, "Deathlok");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (178, 2, 17, "Gambit");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (179, 2, 18, "Psylocke");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (180, 2, 19, "Vision");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (181, 2, 20, "Hawkeye");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (182, 2, 21, "Silver Sable");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (183, 2, 22, "Nigth Thrasher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (184, 2, 23, "Puck");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (185, 2, 24, "Union Jack");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (186, 2, 25, "Quicksilver");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (187, 2, 26, "Scarlet Witch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (188, 2, 27, "Havoc");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (189, 2, 28, "Iron Fist");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (190, 2, 29, "Adam Warlock");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (191, 2, 30, "Wonder Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (192, 2, 31, "Sasquatch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (193, 2, 32, "Firestar");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (194, 2, 33, "Death's Head");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (195, 2, 34, "Speedball");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (196, 2, 35, "USAgent");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (197, 2, 36, "Banshee");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (198, 2, 37, "Meggan");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (199, 2, 38, "Jubilee");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (200, 2, 39, "Ghost Rider");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (201, 2, 40, "Beast");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (202, 2, 41, "Invisible Woman");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (203, 2, 42, "Rogue");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (204, 2, 43, "Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (205, 2, 44, "Doctor Strange");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (206, 2, 45, "Silver Surfer");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (207, 2, 46, "Storm");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (208, 2, 47, "Archangel");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (209, 2, 48, "Thor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (210, 2, 49, "Quasar");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (211, 2, 50, "wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (212, 2, 51, "Cyclops");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (213, 2, 52, "Nick Fury");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (214, 2, 53, "Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (215, 2, 54, "Captain America");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (216, 2, 55, "Kingpin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (217, 2, 56, "Sabretooth");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (218, 2, 57, "Magneto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (219, 2, 58, "Venom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (220, 2, 59, "Galactus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (221, 2, 60, "Mandarin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (222, 2, 61, "Chameleon");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (223, 2, 62, "Super Skrull");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (224, 2, 63, "Grim Reaper");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (225, 2, 64, "Mojo");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (226, 2, 65, "Fin Fang Foom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (227, 2, 66, "Jigsaw");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (228, 2, 67, "Tombstone");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (229, 2, 68, "Ulik");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (230, 2, 69, "Baron Strucker");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (231, 2, 70, "Mysterio");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (232, 2, 71, "Sauron");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (233, 2, 72, "Annihilus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (234, 2, 73, "Rhino");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (235, 2, 74, "Absorbing Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (236, 2, 75, "Doctor Octopus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (237, 2, 76, "Baron Mordo");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (238, 2, 77, "Saracen");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (239, 2, 78, "Nebula");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (240, 2, 79, "Puma");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (241, 2, 80, "Deathwatch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (242, 2, 81, "Kang");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (243, 2, 82, "Blackout");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (244, 2, 83, "Calypso");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (245, 2, 84, "Ultron");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (246, 2, 85, "Thanos");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (247, 2, 86, "Hobgoblin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (248, 2, 87, "Lizard");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (249, 2, 88, "Doctor Doom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (250, 2, 89, "Loki");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (251, 2, 90, "Red Skull");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (252, 2, 91, "Spider-Man vs Venom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (253, 2, 92, "Fantastic Four vs Skrulls");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (254, 2, 93, "Wolverine vs Sabretooth");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (255, 2, 94, "Silver Surfer vs Galactus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (256, 2, 95, "Daredevil vs Elektra");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (257, 2, 96, "Avengers vs Kang");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (258, 2, 97, "Human Torch vs Sub-Mariner");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (259, 2, 98, "Spider-Man vs Hobgoblin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (260, 2, 90, "Captain America vs Baron Zemo");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (261, 2, 100, "Punisher vs Jigsaw");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (262, 2, 101, "X-Factor vs Apocalypse");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (263, 2, 102, "Punisher vs Kingpin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (264, 2, 103, "Thing vs Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (265, 2, 104, "Daredevil vs Bullseye");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (266, 2, 105, "Spider-Man vs Doctor Octopus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (267, 2, 106, "X-Men vs Sentinels");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (268, 2, 107, "Fantastic Four vs Galactus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (269, 2, 108, "Wolverine vs Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (270, 2, 109, "Ghost Rider vs DeathWatch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (271, 2, 110, "Dr Strange vs Baron Mordo");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (272, 2, 111, "Nick Fury vs Baron Strucker");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (273, 2, 112, "Spider-Man vs Lizard");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (274, 2, 113, "Silver Surfer vs Thanos");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (275, 2, 114, "Avengers vs Ultron");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (276, 2, 115, "Captain America vs Red Skull");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (277, 2, 116, "Daredevil vs Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (278, 2, 117, "X-Men vs Marauders");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (279, 2, 118, "Iron Man vs Mandarin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (280, 2, 119, "Hulk vs Leader");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (281, 2, 120, "Thor vs Loki");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (282, 2, 121, "Spider-Man vs Jonah Jameson");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (283, 2, 122, "Thor vs Ulik");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (284, 2, 123, "Silver Surfer vs Mephisto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (285, 2, 124, "Fantastic Four vs Dr Doom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (286, 2, 125, "X-Men vs Magneto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (287, 2, 126, "Daredevil vs Kingpin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (288, 2, 127, "Captain America's Shield");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (289, 2, 128, "Thor's Hammer");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (290, 2, 129, "Daredevil's Billy Club");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (291, 2, 130, "Ultimate Nullifier");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (292, 2, 131, "Spider-Man's Web Shooters");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (293, 2, 132, "Punisher's Arsenal");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (294, 2, 133, "Iron Man's Armor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (295, 2, 134, "Infinity Gauntlet");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (296, 2, 135, "Quasam's Quantum Bands");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (297, 2, 136, "Dr Octopu's Arms");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (298, 2, 137, "Mandarin's Rings");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (299, 2, 138, "Wolverine's Claws");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (300, 2, 139, "Captain Marvel");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (301, 2, 140, "Bucky");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (302, 2, 141, "Green Goblin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (303, 2, 142, "Original Ghost Rider");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (304, 2, 143, "Kraven");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (305, 2, 144, "Dark Phoenix");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (306, 2, 145, "Darkhawk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (307, 2, 146, "Sleepwalker");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (308, 2, 147, "Rage");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (309, 2, 148, "X-Force");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (310, 2, 149, "New Fantastic Four");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (311, 2, 150, "Fantastic Four");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (312, 2, 151, "Avengers");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (313, 2, 152, "Avengers West Coast");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (314, 2, 153, "X-Men");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (315, 2, 154, "X-Factor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (316, 2, 155, "Excalibur");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (317, 2, 156, "New Warriors");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (318, 2, 157, "Masters of Evil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (319, 2, 158, "Marauders");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (320, 2, 159, "Strength");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (321, 2, 160, "Speed");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (322, 2, 161, "Agility");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (322, 2, 161, "Stamina");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (322, 2, 161, "Durability");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (322, 2, 161, "Inteligence");
