INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (323, 3, 1, "Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (324, 3, 2, "Quasar");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (325, 3, 3, "Sleepwalker");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (326, 3, 4, "Gambit");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (327, 3, 5, "Cannonball");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (328, 3, 6, "Beast");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (329, 3, 7, "Quicksilver");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (330, 3, 8, "Weapon Omega");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (331, 3, 9, "Doctor Strange");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (332, 3, 10, "Major Victory");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (333, 3, 11, "Phoenix");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (334, 3, 12, "Black Widow");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (335, 3, 13, "Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (336, 3, 14, "Sunfire");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (337, 3, 15, "Silver Surfer");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (338, 3, 16, "She-Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (339, 3, 17, "Captain Britain");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (340, 3, 18, "Cage");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (341, 3, 19, "Domino");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (342, 3, 20, "Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (343, 3, 21, "Morbius");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (344, 3, 22, "Nightcrawler");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (345, 3, 23, "Black Panther");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (346, 3, 24, "Ant-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (347, 3, 25, "Ghost Rider");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (348, 3, 26, "Darkhawk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (349, 3, 27, "Iceman");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (350, 3, 28, "Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (351, 3, 29, "Wolfsbane");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (352, 3, 30, "Storm");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (353, 3, 31, "Wonder Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (354, 3, 32, "Moon Knight");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (355, 3, 33, "Mister Fantastic");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (356, 3, 34, "Invisible Woman");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (357, 3, 35, "Shadowcat");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (358, 3, 36, "Warlock");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (359, 3, 37, "Captain America");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (360, 3, 38, "Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (361, 3, 39, "Namor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (362, 3, 40, "Nick Fury");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (363, 3, 41, "Professor X");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (364, 3, 42, "Shatterstar");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (365, 3, 43, "Multiple Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (366, 3, 44, "Blaze");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (367, 3, 45, "Deathlok");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (368, 3, 46, "Colossus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (369, 3, 47, "Meggan");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (370, 3, 48, "Thor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (371, 3, 49, "Namorita");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (372, 3, 50, "Cable");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (373, 3, 51, "Psylocke");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (374, 3, 52, "Warpath");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (375, 3, 53, "Polaris");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (376, 3, 54, "Nomad");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (377, 3, 55, "Charlie-27");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (378, 3, 56, "Thing");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (379, 3, 57, "Longshot");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (380, 3, 58, "Human Torch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (381, 3, 59, "Night Thrasher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (382, 3, 60, "Siryn");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (383, 3, 61, "Nova");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (384, 3, 62, "Iron Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (385, 3, 63, "Archangel");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (386, 3, 64, "Rogue");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (387, 3, 65, "Silver Sable");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (388, 3, 66, "Jean Grey");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (389, 3, 67, "Feral");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (390, 3, 68, "Cyclops");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (391, 3, 69, "Starhawk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (392, 3, 70, "Havok");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (393, 3, 71, "Spider-Man and Human Torch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (394, 3, 72, "Spider-Man and Ghost Rider");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (395, 3, 73, "Spider-Man and Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (396, 3, 74, "Spider-Man and Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (397, 3, 75, "Wolverine and Captain America");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (398, 3, 76, "Wolverine and Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (399, 3, 77, "Wolverine and Cable");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (400, 3, 78, "Magneto and Doctor Doom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (401, 3, 79, "Ghost Rider and Blaze");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (402, 3, 80, "Capatin America and Nomad");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (403, 3, 81, "Spider-Man and Darkhawk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (404, 3, 82, "Iceman and Human Torch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (405, 3, 83, "Captain America and U.S. Agent");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (406, 3, 84, "Wolverine and Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (407, 3, 85, "Vision and Scarlet Witch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (408, 3, 86, "Punisher and Deathlok");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (409, 3, 87, "Thor Corps");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (410, 3, 88, "Wolverine, Ghost Rider and Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (411, 3, 89, "Wonder Man and Beast");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (412, 3, 90, "Ghost Rider and Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (413, 3, 91, "Wolverine and Havok");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (414, 3, 92, "Punisher and Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (415, 3, 93, "Daredevil and Black Widow");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (416, 3, 94, "Punisher and Captain America");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (417, 3, 95, "Spider-Man and Sleepwalker");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (418, 3, 96, "Power-Man and Iron Fist");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (419, 3, 97, "Spider-Man and Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (420, 3, 98, "Hulk and Thing");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (421, 3, 99, "Red Skull and Baron Zemo");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (422, 3, 100, "Juggernaut and Black Tom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (423, 3, 101, "Abomination");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (424, 3, 102, "Zodiak");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (425, 3, 103, "Apocalypse");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (426, 3, 104, "Sphinx");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (427, 3, 105, "Destroyer");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (428, 3, 106, "Red Skull");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (429, 3, 107, "Puppet Master");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (430, 3, 108, "Venom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (431, 3, 109, "Diablo");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (432, 3, 110, "Rose");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (433, 3, 111, "Doctor Doom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (434, 3, 112, "Magneto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (435, 3, 113, "Necrom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (436, 3, 114, "Green Goblin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (437, 3, 115, "Dracula");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (438, 3, 116, "Sauron");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (439, 3, 117, "Cyber");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (440, 3, 118, "Mephisto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (441, 3, 119, "Mad Thinker");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (442, 3, 120, "Carnage");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (443, 3, 121, "Hobgoblin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (444, 3, 122, "Gideon");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (445, 3, 123, "White Queen");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (446, 3, 124, "Omega Red");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (447, 3, 125, "Maelstrom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (448, 3, 126, "Thanos");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (449, 3, 127, "Zarrko");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (450, 3, 128, "Magus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (451, 3, 129, "Sabretooth");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (452, 3, 130, "Kingpin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (453, 3, 131, "Silvermane");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (454, 3, 132, "Cardiac");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (455, 3, 133, "Blackheart");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (456, 3, 134, "Terrax");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (457, 3, 135, "Mister Sinister");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (458, 3, 136, "Slug");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (459, 3, 137, "Hate Monger");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (460, 3, 138, "Crossbones");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (461, 3, 139, "Shiva");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (462, 3, 140, "Blackout");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (463, 3, 141, "Pantheon");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (464, 3, 142, "Slapstick");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (465, 3, 143, "Cerise");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (466, 3, 144, "Darkhold Redeemers");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (467, 3, 145, "Strong Guy");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (468, 3, 146, "Bishop");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (469, 3, 147, "Silhouette");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (470, 3, 148, "Kylun");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (471, 3, 149, "Talon");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (472, 3, 150, "Collector");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (473, 3, 151, "Galactus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (474, 3, 152, "Watcher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (475, 3, 153, "Tribunal");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (476, 3, 154, "Ego");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (477, 3, 155, "Eternity");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (478, 3, 156, "Celestials");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (479, 3, 157, "Death");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (480, 3, 158, "Stranger");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (481, 3, 159, "In-Betweener");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (482, 3, 160, "Epoch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (483, 3, 161, "Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (484, 3, 162, "Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (485, 3, 163, "Silver Surfer");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (486, 3, 164, "Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (487, 3, 165, "Iron Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (488, 3, 166, "Captain America");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (489, 3, 167, "Ghost Rider");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (490, 3, 168, "Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (491, 3, 169, "Fantastic Four");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (492, 3, 170, "Thor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (493, 3, 171, "Avengers");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (494, 3, 172, "X-Force");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (495, 3, 173, "X-Factor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (496, 3, 174, "New Warriors");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (497, 3, 175, "Alpha Flight");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (498, 3, 176, "West Coast Avengers");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (499, 3, 177, "Nightstalkers");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (500, 3, 178, "Guardians of the Galaxy");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (501, 3, 179, "X-Men Gold");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (502, 3, 180, "Excalibur");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (503, 3, 181, "Fantastic four");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (504, 3, 182, "X-Men Blue");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (505, 3, 183, "Serpent Society");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (506, 3, 184, "X-Tinction Agenda");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (507, 3, 185, "Evolutionary War");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (508, 3, 186, "Operation Galactic Storm");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (509, 3, 187, "Secret Wars");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (510, 3, 188, "Inferno");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (511, 3, 189, "Infinity Gauntlet");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (512, 3, 190, "Kree vs Skrull War");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (513, 3, 191, "Atlantis Attacks");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (514, 3, 192, "I Married a Skrull");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (515, 3, 193, "Days of Future Past");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (516, 3, 194, "All Hulks Unite");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (517, 3, 195, "Dark Phoenix Saga");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (518, 3, 196, "The Coming of Galactus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (519, 3, 197, "Death of Gwen Stacy");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (520, 3, 198, "Fall of the Kingpin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (521, 3, 199, "Wedding of Spider-Man");
