INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (1, 1, 1, "Captain America");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (2, 1, 2, "Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (3, 1, 3, "Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (4, 1, 4, "Daredevil");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (5, 1, 5, "Nick Fury");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (6, 1, 6, "Thing");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (7, 1, 7, "Professor X");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (8, 1, 8, "Cyclops");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (9, 1, 9, "Marvel Girl");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (10, 1, 10, "Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (11, 1, 11, "Phoenix");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (12, 1, 12, "Power Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (13, 1, 13, "Dazzler");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (14, 1, 14, "Dagger");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (15, 1, 15, "Quasar");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (16, 1, 16, "Sub-Mariner");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (17, 1, 17, "Hulk (Gray)");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (18, 1, 18, "Thor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (19, 1, 19, "Mister Fantastic");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (20, 1, 20, "Black Panther");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (21, 1, 21, "Archangel");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (22, 1, 22, "Iceman");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (23, 1, 23, "Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (24, 1, 24, "Storm");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (25, 1, 25, "Shadowcat");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (26, 1, 26, "Moon Knight");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (27, 1, 27, "Lockheed");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (28, 1, 28, "Aunt May");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (29, 1, 29, "Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (30, 1, 30, "Cosmic Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (31, 1, 31, "She-Hulk's Motorcycle");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (32, 1, 32, "Silver Surfer");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (33, 1, 33, "Human Torch");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (34, 1, 34, "Doctor Strange");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (35, 1, 35, "Havok");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (36, 1, 36, "Colossus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (37, 1, 37, "Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (38, 1, 38, "Nightcrawler");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (39, 1, 39, "She-Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (40, 1, 40, "Captain Britain");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (41, 1, 41, "Rogue");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (42, 1, 42, "Iron Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (43, 1, 43, "Invisible Woman");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (44, 1, 44, "Punisher's Battle Van");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (45, 1, 45, "Longshot");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (46, 1, 46, "Beast");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (47, 1, 47, "Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (48, 1, 48, "Storm");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (49, 1, 49, "Elektra");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (50, 1, 50, "Cloak");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (51, 1, 51, "Wasp");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (52, 1, 52, "Kingpin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (53, 1, 53, "Baron Zemo");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (54, 1, 54, "Loki");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (55, 1, 55, "Juggernaut");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (56, 1, 56, "Nightmare");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (57, 1, 57, "Sabretooth");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (58, 1, 58, "Electro");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (59, 1, 59, "Doctor Octopus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (60, 1, 60, "Doctor Doom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (61, 1, 61, "Ultron");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (62, 1, 62, "Enchantress");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (63, 1, 63, "Magneto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (64, 1, 64, "Bullseye");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (65, 1, 65, "Mister Sinister");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (66, 1, 66, "Sandman");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (67, 1, 67, "Lizard");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (68, 1, 68, "Mole Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (69, 1, 69, "Dormammu");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (70, 1, 70, "Leader");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (71, 1, 71, "Blob");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (72, 1, 72, "Black Cat");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (73, 1, 73, "Venom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (74, 1, 74, "Green Goblin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (75, 1, 75, "Galactus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (76, 1, 76, "Mandarin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (77, 1, 77, "High Evolutionary");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (78, 1, 78, "Mephisto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (79, 1, 79, "Thanos");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (80, 1, 80, "Apocalypse");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (81, 1, 81, "Red Skull");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (82, 1, 82, "Ghost Rider");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (83, 1, 83, "Deathlok");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (84, 1, 84, "Guardians of the Galaxy");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (85, 1, 85, "New Warriors");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (86, 1, 86, "Nomad");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (87, 1, 87, "Foolkiller");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (88, 1, 88, "Thing vs Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (89, 1, 89, "Fantastic Four vs Galactus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (90, 1, 90, "Fantastic Four vs Doctor Doom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (91, 1, 91, "Thor vs Surtur");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (92, 1, 92, "Spider-Man vs Kraven");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (93, 1, 93, "Spider-Man vs Doctor Octopus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (94, 1, 94, "Daredevil vs Bullseye");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (95, 1, 95, "Daredevil vs Kingpin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (96, 1, 96, "Silver Surfer vs Mephisto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (97, 1, 97, "Captain America vs Red Skull");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (98, 1, 98, "Dark Phoenix Saga");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (99, 1, 90, "X-Men vs Avengers");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (100, 1, 100, "X-Men vs Magneto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (101, 1, 101, "X-Men vs Fantastic Four");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (102, 1, 102, "Fall of the Mutants");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (103, 1, 103, "Evolutionary War");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (104, 1, 104, "Atlantis Attacks");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (105, 1, 105, "Acts of Vengeance");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (106, 1, 106, "Spider-Man vs Venom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (107, 1, 107, "Nick Fury vs Hydra");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (108, 1, 108, "Armor Wars");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (109, 1, 109, "Daredevil vs Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (110, 1, 110, "Daredevil vs Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (111, 1, 111, "Spider-Man vs Green Golbin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (112, 1, 112, "Spider-Man vs Hobgolbin");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (113, 1, 113, "Hulk vs Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (114, 1, 114, "Hulk vs Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (115, 1, 115, "Captain America vs Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (116, 1, 116, "Silver Surfer vs Thanos");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (117, 1, 117, "X-Factor vs Apocalypse");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (118, 1, 118, "X-Men vs Freedom Force");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (119, 1, 119, "Wolverine vs Sabretooth");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (120, 1, 120, "X-Men in the Savage Land");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (121, 1, 121, "Iron Man vs Titanium Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (122, 1, 122, "Thor vs Loki");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (123, 1, 123, "Kree-Skrull War");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (124, 1, 124, "Fantastic Four #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (125, 1, 125, "X-Men #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (126, 1, 126, "Amazing Fantasy #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (127, 1, 127, "Punisher #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (128, 1, 128, "Journey Into Mystery #83");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (129, 1, 129, "Amazing Spider-Man #129");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (130, 1, 130, "Avengers #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (131, 1, 131, "Amazing Spider-Man #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (132, 1, 132, "Giant Size X-Men #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (133, 1, 133, "Wolverine Limited Series #1");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (134, 1, 134, "Incredible Hulk #181");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (135, 1, 135, "Tales of Suspense #39");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (136, 1, 136, "Avengers #4");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (137, 1, 137, "Fantastic Four");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (138, 1, 138, "Avengers");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (139, 1, 139, "X-Men");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (140, 1, 140, "X-Men");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (141, 1, 141, "Cloak and Dagger");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (142, 1, 142, "New Mutants");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (143, 1, 143, "X-Factor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (144, 1, 144, "Excalibur");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (145, 1, 145, "Brotherhood of Evil Mutants");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (146, 1, 146, "Sinister Six");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (147, 1, 147, "Hellfire Club");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (148, 1, 148, "Alpha Flight");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (149, 1, 149, "SP Spider-Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (150, 1, 150, "SP Doctor Doom");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (151, 1, 151, "SP Doctor Octopus");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (152, 1, 152, "SP Hulk");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (153, 1, 153, "SP Silver Surfer");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (154, 1, 154, "SP Thor");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (155, 1, 155, "SP Punisher");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (156, 1, 156, "SP Magneto");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (157, 1, 157, "SP Captain America");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (158, 1, 158, "SP Doctor Strange");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (159, 1, 159, "SP Iron Man");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (160, 1, 160, "SP Wolverine");
INSERT INTO Sticker (id, sticker_album_id, number, name) VALUES (161, 1, 161, "SP Mr Marvel");
